/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WfgenAspxImport } from './routes/wfgen.$aspx'
import { Route as WfgenWfappsWebformsProcessVersionAspxImport } from './routes/wfgen.wfapps.webforms.$process.$version.$aspx'

// Create/Update Routes

const WfgenAspxRoute = WfgenAspxImport.update({
  id: '/wfgen/$aspx',
  path: '/wfgen/$aspx',
  getParentRoute: () => rootRoute,
} as any)

const WfgenWfappsWebformsProcessVersionAspxRoute =
  WfgenWfappsWebformsProcessVersionAspxImport.update({
    id: '/wfgen/wfapps/webforms/$process/$version/$aspx',
    path: '/wfgen/wfapps/webforms/$process/$version/$aspx',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wfgen/$aspx': {
      id: '/wfgen/$aspx'
      path: '/wfgen/$aspx'
      fullPath: '/wfgen/$aspx'
      preLoaderRoute: typeof WfgenAspxImport
      parentRoute: typeof rootRoute
    }
    '/wfgen/wfapps/webforms/$process/$version/$aspx': {
      id: '/wfgen/wfapps/webforms/$process/$version/$aspx'
      path: '/wfgen/wfapps/webforms/$process/$version/$aspx'
      fullPath: '/wfgen/wfapps/webforms/$process/$version/$aspx'
      preLoaderRoute: typeof WfgenWfappsWebformsProcessVersionAspxImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/wfgen/$aspx': typeof WfgenAspxRoute
  '/wfgen/wfapps/webforms/$process/$version/$aspx': typeof WfgenWfappsWebformsProcessVersionAspxRoute
}

export interface FileRoutesByTo {
  '/wfgen/$aspx': typeof WfgenAspxRoute
  '/wfgen/wfapps/webforms/$process/$version/$aspx': typeof WfgenWfappsWebformsProcessVersionAspxRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/wfgen/$aspx': typeof WfgenAspxRoute
  '/wfgen/wfapps/webforms/$process/$version/$aspx': typeof WfgenWfappsWebformsProcessVersionAspxRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/wfgen/$aspx' | '/wfgen/wfapps/webforms/$process/$version/$aspx'
  fileRoutesByTo: FileRoutesByTo
  to: '/wfgen/$aspx' | '/wfgen/wfapps/webforms/$process/$version/$aspx'
  id:
    | '__root__'
    | '/wfgen/$aspx'
    | '/wfgen/wfapps/webforms/$process/$version/$aspx'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  WfgenAspxRoute: typeof WfgenAspxRoute
  WfgenWfappsWebformsProcessVersionAspxRoute: typeof WfgenWfappsWebformsProcessVersionAspxRoute
}

const rootRouteChildren: RootRouteChildren = {
  WfgenAspxRoute: WfgenAspxRoute,
  WfgenWfappsWebformsProcessVersionAspxRoute:
    WfgenWfappsWebformsProcessVersionAspxRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/wfgen/$aspx",
        "/wfgen/wfapps/webforms/$process/$version/$aspx"
      ]
    },
    "/wfgen/$aspx": {
      "filePath": "wfgen.$aspx.tsx"
    },
    "/wfgen/wfapps/webforms/$process/$version/$aspx": {
      "filePath": "wfgen.wfapps.webforms.$process.$version.$aspx.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
